### ISSUE TITLE
Please Update to Latest rubygems

### ISSUE THREAD

**Issue by thefringeninja** [carolynvs/chocolatey-packages#4]
Getting an error with 2.2.2 of rubygems:

ERROR:  Could not find a valid gem 'rails' (= 3.2.14), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://s3.amazonaws.com/production.s3.rubygems.org/specs.4.8.gz)

http://stackoverflow.com/questions/19150017/ssl-error-when-installing-rubygems-unable-to-pull-data-from-https-rubygems-o

**Comment by carolynvs** [comment]
It's still awaiting moderation but if you specify the version, you can get the latest of the package, https://chocolatey.org/packages/rubygems/2.4.6.
